// Generated by dts-bundle v0.7.3

declare module 'trapezium' {
    import TrapeziumOptions from "trapezium/models/options";
    import TrapeziumResult from "trapezium/models/result";
    export function trapezium(element: HTMLElement | JQuery, userOptions?: TrapeziumOptions): TrapeziumResult;
    export default trapezium;
}

declare module 'trapezium/models/options' {
    export interface TrapeziumOptions {
        useDocument?: boolean;
    }
    export default TrapeziumOptions;
}

declare module 'trapezium/models/result' {
    export type Sides = "top" | "right" | "bottom" | "left";
    export interface TrapeziumResult {
        horizontal: "equal" | "left" | "right";
        vertical: "equal" | "top" | "bottom";
        best: "equal" | "horizontal" | "vertical" | Sides;
    }
    export default TrapeziumResult;
}

