var path = require("path");
var webpack = require("webpack");
/**
 * Config for test environment is pretty different from dev and prod, so we don"t use common config as base.
 *
 * Karma watches the test entry points, so we don"t need to define entry point here.
 */
module.exports = {
    /**
     * Inline source maps, generated by TypeScript compiler, will be used for code coverage.
     */
    devtool: "inline-source-map",

    resolve: {
        extensions: [".ts", ".tsx", ".js", ".scss", ".html"],
        modules: ["node_modules", "src", "tests", "typings"]
    },

    module: {
        rules: [
            /**
             * Enable inline source maps for code coverage report.
             *
             * See project repository for details / configuration reference:
             * https://github.com/s-panferov/awesome-typescript-loader
             */
            {
                test: /\.ts(x?)$/,
                use: [
                    "ts-loader",
                ],
            },
            /**
             * These loaders are used in other environments as well.
             */
            {
                test: /\.json$/,
                use: [
                    "json-loader",
                ],
            },
            {
                test: /\.html$/,
                use: [
                    {
                        loader: "html-loader",
                        options: {
                            exportAsEs6Default: true,
                        }
                    }
                ],
            },
            {
                test: /\.scss$/,
                use: [
                    "style-loader",
                    "css-loader",
                    "sass-loader",
                ],
            },
            /**
             * Instruments TS source files for subsequent code coverage.
             * See https://github.com/deepsweet/istanbul-instrumenter-loader
             */
            {
                enforce: "post",
                test: /\.ts(x?)$/,
                use: [
                    "istanbul-instrumenter-loader",
                ],
                include: path.resolve("src/"),
            },
        ],
    },

    plugins: [
        new webpack.NormalModuleReplacementPlugin(/^\.\/package$/, function (result) {
            if (/cheerio/.test(result.context)) {
                result.request = "./package.json";
            }
        })
    ],

    externals: {
        "react/addons": true,
        "react/lib/ExecutionEnvironment": true,
        "react/lib/ReactContext": "window",
        "text-encoding": "window"
    },
};
